global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'Kafka metrics'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [
        '127.0.0.1:8181',
      ]
        labels:
          group: 'kafka'
